steps:
  # Paso único: build y push directamente con buildx
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --use
        docker buildx build --platform linux/amd64 \
          -t us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe \
          --push .

  # Paso 2: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy read-dataframe \
          --image=us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --project=proyecto-1-461620

images:
  - us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe

options:
  logging: CLOUD_LOGGING_ONLY