steps:
  # Paso 1: Build de imagen estándar (funciona bien en Cloud Build)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe',
        '.'
      ]

  # Paso 2: Push a Artifact Registry (funciona si el SA tiene permisos, como ya lo configuraste)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe'
      ]

  # Paso 3: Despliegue en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy read-dataframe \
          --image=us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --project=proyecto-1-461620

images:
  - us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe

options:
  logging: CLOUD_LOGGING_ONLY