steps:
  # Paso 1: Build & push usando Kaniko
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - "--destination=us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe:latest"
      - "--context=."
      - "--dockerfile=Dockerfile"
      - "--verbosity=info"

  # Paso 2: Esperar antes de desplegar
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args: ["-c", "echo 'Esperando 20 segundos para asegurar disponibilidad de imagen...'; sleep 20"]

  # Paso 3: Despliegue en Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy read-dataframe \
          --image=us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe:latest \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --project=proyecto-1-461620

#images:
#  - us-central1-docker.pkg.dev/proyecto-1-461620/my-functions-repo/read-dataframe:latest

options:
  logging: CLOUD_LOGGING_ONLY